### ISSUE TITLE
How does the code recognize an item deposit.

### ISSUE THREAD

**Issue by ptran099** [D3uxx/csgojackpotV2#4]
I'm familiar with programming, but not so much in web development and have been looking through the code. Is there a specific part in the code that recognizes when an item has been deposited in the inventory and counts it as a deposit?

**Comment by c0deina** [comment]
That's the bot that does that, I'll be uploading it tomorrow late.

**Comment by ChristophWeigert** [comment]
Can you upload the bot? 

Currently I am rewriting this with .NET WebApi, EF and Angular.
